### ISSUE TITLE
Crear un manual de uso documentación de la aplicación

### ISSUE THREAD

**Issue by RdzSebastian** [RdzSebastian/agendaza-frontend-ps#15]

**Comment by Ariel-Santillan** [comment]
@RdzSebastian el dashboard es una función que todos los usuarios van a poder acceder o sólo los admin?

**Comment by RdzSebastian** [comment]
Solo los "admin" deberían tener acceso a todo
Los "usuarios finales" (cosa aún no implementada y muy a futuro) deberían ver como un dashboard de sus contrataciones
Por otro lado están los “encargados” deberían ver un reducido al que ve el "admin"

- "Admin" puede crear, borrar, modificar y editar: extras, catering, tipo de evento, empleados, servicios, empresas
- "Encargado" solo debería ver: pagos, buscar evento, clientes

Ósea la necesario para que si viene un "cliente" o "x" pueda gestionarle las dudas que tenga y agregar un pago o editar su evento
