### ISSUE TITLE
Crear vista para visualización de clientes

### ISSUE THREAD

**Issue by RdzSebastian** [RdzSebastian/agendaza-frontend-ps#23]

**Comment by RdzSebastian** [comment]
Adjunto imagen de como se debería ver aprox la vista.

Esta vista aparece al tocar en el icono del ojo que esta al lado de "cliente" dentro de "ver evento" de "buscar evento", en el dashbord

![Image](https://github.com/RdzSebastian/agendaza-frontend-ps/assets/33104372/d89e86d7-22b5-47a0-97ca-8039c4286fc6)

**Comment by RdzSebastian** [comment]
Adjunto html base de maquetacion:

Lo que habria que tener en cuenta es que "Volver" deberia ir a la derecha de "Ver cliente" 
Adjunto foto de ejemplo del panel de administracion



![Image](https://github.com/RdzSebastian/agendaza-frontend-ps/assets/33104372/35aa6ddc-22d3-41bf-9ab8-fd2b9ca2b0e7)



```

<div class="container">
	<br>
	<h2>Ver Cliente</h2>
       	<div class="row">
    		<div class="col-md-6">
			<div class="form-group col-6 mb-4">
				<h5>Cliente</h5>
				<div class="row">
					<div class="col-10">
			                    <input type="text" class="form-control" value="-, GISELA" readonly="">
					</div>
					<div class="col-2">
						<a class="mx-2" title="Editar" href="/saveCliente/39" data-toggle="tooltip"><i class="fas fa-edit text-warning fa-lg"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-9">
				<div>
				    <table class="table table-bordered">
						<thead>
							<tr>
								<th>Evento</th>
								<th>Codigo</th>
								<th class="text-center">Acciones</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>INFANTIL CIELO</td>
								<td>SVNC</td>
								<td class="text-center">
									<a class="mx-2" title="Ver" href="/verEvento/47" data-toggle="tooltip"><i class="fas fa-eye text-primary"></i></a>
								</td>
							</tr>
						</tbody>
					</table>
		        	</div>
            		</div>
		</div>
       	</div>

	<div class="container mt-3">
		<div class="gap-2 d-flex justify-content-end">
			<div>
				<a href="../verEvento/47" class="btn btn-primary">Volver</a>
			</div>
		</div>
	</div>
</div>
```

**Comment by Ariel-Santillan** [comment]
Commit de front con tabla de eventos por cliente: https://github.com/RdzSebastian/agendaza-frontend-ps/commit/96e6241b19c5a4127d8eadde7ecaa020b9d5291b

Commit de back con nuevo endpoint usado: https://github.com/RdzSebastian/agendaza-backend-ps/commit/27051c79abb545552698346b6130287149064e08

En el back se me creó una rama "Develop" en lugar de "develop", que igualmente tiene los últimos cambios de "develop", no debería fallar el merge

**Comment by Ariel-Santillan** [comment]
PR front: https://github.com/RdzSebastian/agendaza-frontend-ps/pull/29

PR back: https://github.com/RdzSebastian/agendaza-backend-ps/pull/8
