### ISSUE TITLE
Ajustes vista visualización cliente

### ISSUE THREAD

**Issue by RdzSebastian** [RdzSebastian/agendaza-frontend-ps#33]

**Comment by RdzSebastian** [comment]
- El botón ver evento siempre lleva al mismo evento. Debería tener el id del evento al que quiero visualizar y llevar a el
- Mostrar un máximo de 10 eventos y en caso de haber mas poner una leyenda abajo "X eventos mas contratados"
   `` <small class="form-text text-muted">X eventos contratados</small> ``
  donde x es la cantidad total de los eventos contratados

- Achicar el botón "volver" a tamaño referencia del volver de "ver evento"

**Comment by Ariel-Santillan** [comment]
Todo corregido menos el botón de Ver evento lleva siempre al mismo evento.

En el código tiene el id dinámico y puedo ver que llega el valor que corresponde a cada uno, pero igualmente redirige a uno sólo. Les pido ayuda para revisar eso porfa

**Comment by RdzSebastian** [comment]
- El botón ver evento siempre lleva al mismo evento. Debería tener el id del evento al que quiero visualizar y llevar a el

- Mostrar un máximo de 10 eventos y en caso de haber mas poner una leyenda abajo "X eventos mas contratados"
<small class="form-text text-muted">X eventos contratados</small>
donde x es la cantidad total de los eventos contratados

**Comment by Ariel-Santillan** [comment]
Corrige máximo de eventos a mostrar a 10

**Comment by RdzSebastian** [comment]
Listo, ajustes realizados para correcto funcionamiento
